server:
  port: 8001
 
spring:
  application:
    name: spring-cloud-demo
 
#注册中心指向start    
eureka:
  instance:
    instance-id: spring-cloud-demo
    appname: ${spring.application.name}
word: ddd